### ISSUE TITLE
没有激活邮件

### ISSUE THREAD

**Issue by oMahiro** [viva-la-vita/bbs#3]
账号激活邮件已发送至   ，请激活账号，若未收到请检查垃圾箱。
垃圾箱没有，各种邮箱都试过了。

**Comment by oMahiro** [comment]
![图片](https://github.com/user-attachments/assets/446333b1-e545-4d55-83f1-8fa58cc396e8)

**Comment by tansongchen** [comment]
目前邮件发送功能已经恢复正常，如果仍无法注册，可以重新开启本 issue。
